### ISSUE TITLE
Hello the automatic script doesn't work anymore, I have this error :

### ISSUE THREAD

**Issue by antoinerzad** [xuac/claim-epic-freebies#4]
Hello the automatic script doesn't work anymore, I have this error :

`
yarn start *** *** 0 ***
  shell: /bin/bash -e {0}
yarn run v1.22.4
$ node claimer.js *** *** 0 ***
 2020-08-16 | 18:59:22.724 | ERROR | { Error: ENOENT: no such file or directory, mkdir '/home/runner/work/claim-epic-freebies/claim-epic-freebies/.egstore/b60e62be8f01d1f927f45690555ccd86ca6edcd8a0f8c97b0466048ba97acc02'
    at Object.mkdirSync (fs.js:757:3)
    at new Launcher (/home/runner/work/claim-epic-freebies/claim-epic-freebies/node_modules/epicgames-client/src/Client/index.js:108:10)
    at /home/runner/work/claim-epic-freebies/claim-epic-freebies/claimer.js:70:26
    at process._tickCallback (internal/process/next_tick.js:68:7)
  errno: -2,
  syscall: 'mkdir',
  code: 'ENOENT',
  path:
   '/home/runner/work/claim-epic-freebies/claim-epic-freebies/.egstore/b60e62be8f01d1f927f45690555ccd86ca6edcd8a0f8c97b0466048ba97acc02' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
`

**Comment by xuac** [comment]
Fixed in #5 

@antoinerzad  Delete your fork and follow the steps again.

**Comment by JourneyOver** [comment]
I think something changed on Epics side of things anyways recently that Revadike needs to fix in his script as literally everyone's (including mine) github actions have been failing even with this fix in place. 

All it does now is just throw the `Error: Failed to launch the browser process!` error on github actions (can view anyone's fork who has the `.egstore` fix in it and see it's failing always) and it's been going on like this for a while now.

**Comment by xuac** [comment]
I think Epic Games is now enforcing captcha while logging in which breaks the script.

![image](https://user-images.githubusercontent.com/69117518/90601450-dbeaa500-e215-11ea-8fda-aa30aca671bb.png)

**Comment by JourneyOver** [comment]
Figures as much, sucks as I would of loved to continue using the script since I didn't have to worry about grabbing the games.
